import Link from 'next/link';
import { apiFetch, ApiError } from '@/lib/api/server-client';
import type { AuditListResponse } from '@/lib/api/types';
import { Alert } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { PageHeader } from '@/components/layout/page-header';
import { Button } from '@/components/ui/button';
import { formatDateTime, shortId } from '@/lib/utils';

export const metadata = { title: 'Audit log' };

const ACTIONS = ['INSERT', 'UPDATE', 'DELETE'] as const;

export default async function AuditPage({
  searchParams,
}: {
  searchParams?: {
    action?: string;
    tableName?: string;
    cursor?: string;
  };
}) {
  const params = new URLSearchParams();
  if (searchParams?.action) params.set('action', searchParams.action);
  if (searchParams?.tableName) params.set('tableName', searchParams.tableName);
  if (searchParams?.cursor) params.set('cursor', searchParams.cursor);
  params.set('limit', '50');

  let data: AuditListResponse | null = null;
  let error: string | null = null;
  try {
    data = await apiFetch<AuditListResponse>(`/audit?${params.toString()}`, {
      authenticated: true,
    });
  } catch (e) {
    error = e instanceof ApiError ? e.payload.message : 'Failed to load audit log';
  }

  return (
    <>
      <PageHeader
        eyebrow="Compliance"
        title="Audit log"
        description="An append-only record of every change in the system. Generated by database triggers — not application code — so the trail cannot be bypassed. Sensitive fields are redacted before they reach this log."
      />

      {error && (
        <Alert variant="danger" title="Could not load audit log">
          {error}
        </Alert>
      )}

      <form
        className="mb-5 flex flex-wrap items-end gap-3"
        action="/dashboard/audit"
      >
        <div className="space-y-1">
          <label className="block text-[10px] font-medium uppercase tracking-[0.14em] text-ink-500">
            Action
          </label>
          <select
            name="action"
            defaultValue={searchParams?.action ?? ''}
            className="h-10 rounded-sm border border-ink-200 bg-white px-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent"
          >
            <option value="">All</option>
            {ACTIONS.map((a) => (
              <option key={a} value={a}>
                {a}
              </option>
            ))}
          </select>
        </div>
        <div className="space-y-1">
          <label className="block text-[10px] font-medium uppercase tracking-[0.14em] text-ink-500">
            Table
          </label>
          <input
            name="tableName"
            defaultValue={searchParams?.tableName ?? ''}
            placeholder="e.g. users"
            className="h-10 w-48 rounded-sm border border-ink-200 bg-white px-3 text-sm placeholder:text-ink-400 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent"
          />
        </div>
        <Button type="submit" variant="outline">
          Filter
        </Button>
        {(searchParams?.action || searchParams?.tableName) && (
          <Button asChild variant="ghost">
            <Link href="/dashboard/audit">Clear</Link>
          </Button>
        )}
      </form>

      {data && (
        <div className="overflow-hidden rounded-sm border border-ink-200 bg-white">
          <table className="w-full border-collapse text-sm">
            <thead>
              <tr className="border-b border-ink-200 bg-ink-50/40 text-left">
                <Th>Time</Th>
                <Th>Actor</Th>
                <Th>Action</Th>
                <Th>Table</Th>
                <Th>Record</Th>
                <Th>Changed fields</Th>
              </tr>
            </thead>
            <tbody>
              {data.items.length === 0 && (
                <tr>
                  <td colSpan={6} className="px-4 py-12 text-center text-sm text-ink-500">
                    No audit entries match these filters.
                  </td>
                </tr>
              )}
              {data.items.map((r) => (
                <tr
                  key={r.id}
                  className="border-b border-ink-100 transition-colors last:border-0 hover:bg-ink-50/40"
                >
                  <Td>
                    <span className="font-mono text-xs text-ink-600">
                      {formatDateTime(r.occurredAt)}
                    </span>
                  </Td>
                  <Td>
                    <div className="text-xs">
                      <div className="font-medium text-ink-800">
                        {r.actorEmail ?? <span className="italic text-ink-400">system</span>}
                      </div>
                      <div className="font-mono text-ink-500">{shortId(r.actorUserId)}</div>
                    </div>
                  </Td>
                  <Td>
                    <ActionBadge action={r.action} />
                  </Td>
                  <Td>
                    <span className="font-mono text-xs text-ink-700">{r.tableName}</span>
                  </Td>
                  <Td>
                    <span className="font-mono text-xs text-ink-700">{shortId(r.recordId)}</span>
                  </Td>
                  <Td>
                    {r.changedFields.length === 0 ? (
                      <span className="text-xs text-ink-400">—</span>
                    ) : (
                      <div className="flex flex-wrap gap-1">
                        {r.changedFields.slice(0, 5).map((f) => (
                          <Badge key={f} variant="outline">
                            <span className="font-mono text-[10px]">{f}</span>
                          </Badge>
                        ))}
                        {r.changedFields.length > 5 && (
                          <Badge variant="outline">
                            +{r.changedFields.length - 5}
                          </Badge>
                        )}
                      </div>
                    )}
                  </Td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {data?.nextCursor && (
        <div className="mt-4 text-right">
          <Button asChild variant="outline">
            <Link
              href={{
                pathname: '/dashboard/audit',
                query: {
                  ...(searchParams?.action ? { action: searchParams.action } : {}),
                  ...(searchParams?.tableName ? { tableName: searchParams.tableName } : {}),
                  cursor: data.nextCursor,
                },
              }}
            >
              Load more
            </Link>
          </Button>
        </div>
      )}
    </>
  );
}

function ActionBadge({ action }: { action: string }) {
  const variant: 'success' | 'warning' | 'danger' | 'default' =
    action === 'INSERT'
      ? 'success'
      : action === 'UPDATE'
        ? 'warning'
        : action === 'DELETE'
          ? 'danger'
          : 'default';
  return <Badge variant={variant}>{action}</Badge>;
}

function Th({ children }: { children: React.ReactNode }) {
  return (
    <th className="px-4 py-3 text-[10px] font-medium uppercase tracking-[0.14em] text-ink-500">
      {children}
    </th>
  );
}
function Td({ children }: { children: React.ReactNode }) {
  return <td className="px-4 py-3 align-top">{children}</td>;
}
