import Link from 'next/link';
import type React from 'react';
import { Activity, AlertTriangle, CalendarDays, Database, FileSearch, ShieldCheck, UserRound } from 'lucide-react';
import { apiFetch, ApiError } from '@/lib/api/server-client';
import type { AuditEntry, AuditListResponse } from '@/lib/api/types';
import { Alert } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { PageHeader } from '@/components/layout/page-header';
import { Button } from '@/components/ui/button';
import { formatDateTime, shortId } from '@/lib/utils';

export const metadata = { title: 'Audit log' };

const ACTIONS = ['INSERT', 'UPDATE', 'DELETE'] as const;
const QUICK_TABLES = [
  { label: 'Registrations', value: 'handler_registrations' },
  { label: 'Payments', value: 'payments' },
  { label: 'Medical', value: 'medical_screenings' },
  { label: 'Certificates', value: 'certificates' },
  { label: 'Template', value: 'tenant_settings' },
  { label: 'Users', value: 'users' },
];

export default async function AuditPage({
  searchParams,
}: {
  searchParams?:
    | {
        action?: string;
        tableName?: string;
        fromDate?: string;
        toDate?: string;
        cursor?: string;
      }
    | Promise<{
        action?: string;
        tableName?: string;
        fromDate?: string;
        toDate?: string;
        cursor?: string;
      }>;
}) {
  const resolvedSearchParams = await Promise.resolve(searchParams);
  const params = new URLSearchParams();
  if (resolvedSearchParams?.action) params.set('action', resolvedSearchParams.action);
  if (resolvedSearchParams?.tableName) params.set('tableName', resolvedSearchParams.tableName);
  if (resolvedSearchParams?.fromDate) params.set('fromDate', resolvedSearchParams.fromDate);
  if (resolvedSearchParams?.toDate) params.set('toDate', resolvedSearchParams.toDate);
  if (resolvedSearchParams?.cursor) params.set('cursor', resolvedSearchParams.cursor);
  params.set('limit', '50');

  let data: AuditListResponse | null = null;
  let error: string | null = null;
  try {
    data = await apiFetch<AuditListResponse>(`/audit?${params.toString()}`, {
      authenticated: true,
    });
  } catch (e) {
    error = e instanceof ApiError ? e.payload.message : 'Failed to load audit log';
  }

  const items = data?.items ?? [];
  const summary = buildSummary(items);
  const activeFilters = [
    resolvedSearchParams?.action ? `Action: ${resolvedSearchParams.action}` : null,
    resolvedSearchParams?.tableName ? `Table: ${resolvedSearchParams.tableName}` : null,
    resolvedSearchParams?.fromDate ? `From: ${resolvedSearchParams.fromDate}` : null,
    resolvedSearchParams?.toDate ? `To: ${resolvedSearchParams.toDate}` : null,
  ].filter(Boolean) as string[];

  return (
    <>
      <PageHeader
        eyebrow="Compliance"
        title="Audit log"
        description="An append-only record of every change in the system. Generated by database triggers, not application code, so the trail cannot be bypassed. Sensitive fields are redacted before they reach this log."
      />

      {error && (
        <Alert variant="danger" title="Could not load audit log">
          {error}
        </Alert>
      )}

      <section className="mb-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <Metric icon={Activity} label="Entries loaded" value={items.length.toLocaleString()} detail={data?.nextCursor ? 'More entries available' : 'Current result set'} />
        <Metric icon={ShieldCheck} label="Updates" value={String(summary.updates)} detail="records edited" />
        <Metric icon={AlertTriangle} label="Deletes" value={String(summary.deletes)} detail="records removed" danger={summary.deletes > 0} />
        <Metric icon={Database} label="Tables touched" value={String(summary.tables)} detail="within this view" />
      </section>

      <section className="mb-5 rounded-sm border border-ink-200 bg-white p-4">
        <form
          className="grid gap-3 sm:grid-cols-2 lg:grid-cols-[auto_minmax(11rem,1fr)_auto_auto_auto]"
          action="/dashboard/audit"
        >
          <div className="space-y-1">
            <label className="block text-[10px] font-medium uppercase tracking-[0.14em] text-ink-500">
              Action
            </label>
            <select
              name="action"
              defaultValue={resolvedSearchParams?.action ?? ''}
              className="h-10 w-full rounded-sm border border-ink-200 bg-white px-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent"
            >
              <option value="">All</option>
              {ACTIONS.map((action) => (
                <option key={action} value={action}>
                  {action}
                </option>
              ))}
            </select>
          </div>
          <div className="space-y-1">
            <label className="block text-[10px] font-medium uppercase tracking-[0.14em] text-ink-500">
              Table
            </label>
            <input
              name="tableName"
              defaultValue={resolvedSearchParams?.tableName ?? ''}
              placeholder="e.g. certificates"
              className="h-10 w-full rounded-sm border border-ink-200 bg-white px-3 text-sm placeholder:text-ink-400 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent"
            />
          </div>
          <DateField name="fromDate" label="From" value={resolvedSearchParams?.fromDate ?? ''} />
          <DateField name="toDate" label="To" value={resolvedSearchParams?.toDate ?? ''} />
          <div className="flex items-end gap-2">
            <Button type="submit" variant="outline">
              Filter
            </Button>
            {activeFilters.length > 0 && (
              <Button asChild variant="ghost">
                <Link href="/dashboard/audit">Clear</Link>
              </Button>
            )}
          </div>
        </form>

        <div className="mt-4 flex flex-wrap gap-2 border-t border-ink-100 pt-4">
          {QUICK_TABLES.map((table) => (
            <Button key={table.value} asChild variant={resolvedSearchParams?.tableName === table.value ? 'default' : 'outline'} size="sm">
              <Link href={`/dashboard/audit?tableName=${encodeURIComponent(table.value)}`}>{table.label}</Link>
            </Button>
          ))}
        </div>

        {activeFilters.length > 0 && (
          <div className="mt-4 flex flex-wrap gap-2">
            {activeFilters.map((filter) => (
              <Badge key={filter} variant="accent">{filter}</Badge>
            ))}
          </div>
        )}
      </section>

      {data && (
        <div className="overflow-hidden rounded-sm border border-ink-200 bg-white shadow-sm">
          <div className="border-b border-ink-100 p-4">
            <div className="flex items-center gap-3">
              <FileSearch className="h-5 w-5 text-accent" />
              <div>
                <h2 className="text-sm font-semibold text-ink-900">Recent Audit Events</h2>
                <p className="text-xs text-ink-500">Showing newest events first. Use filters for investigation work.</p>
              </div>
            </div>
          </div>
          <table className="w-full border-collapse text-sm">
            <thead>
              <tr className="border-b border-ink-200 bg-ink-50/40 text-left">
                <Th>Time</Th>
                <Th>Actor</Th>
                <Th>Action</Th>
                <Th>Table</Th>
                <Th>Record</Th>
                <Th>Changed fields</Th>
              </tr>
            </thead>
            <tbody>
              {data.items.length === 0 && (
                <tr>
                  <td colSpan={6} className="px-4 py-12 text-center text-sm text-ink-500">
                    No audit entries match these filters.
                  </td>
                </tr>
              )}
              {data.items.map((record) => (
                <tr
                  key={record.id}
                  className="border-b border-ink-100 transition-colors last:border-0 hover:bg-ink-50/40"
                >
                  <Td>
                    <span className="font-mono text-xs text-ink-600">
                      {formatDateTime(record.occurredAt)}
                    </span>
                  </Td>
                  <Td>
                    <div className="text-xs">
                      <div className="font-medium text-ink-800">
                        {record.actorEmail ?? <span className="italic text-ink-400">system</span>}
                      </div>
                      <div className="mt-1 flex items-center gap-1 font-mono text-ink-500">
                        <UserRound className="h-3 w-3" />
                        {shortId(record.actorUserId)}
                      </div>
                    </div>
                  </Td>
                  <Td>
                    <ActionBadge action={record.action} />
                  </Td>
                  <Td>
                    <span className="font-mono text-xs text-ink-700">{record.tableName}</span>
                  </Td>
                  <Td>
                    <span className="font-mono text-xs text-ink-700">{shortId(record.recordId)}</span>
                  </Td>
                  <Td>
                    <ChangedFields fields={record.changedFields} />
                  </Td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {data?.nextCursor && (
        <div className="mt-4 text-right">
          <Button asChild variant="outline">
            <Link
              href={{
                pathname: '/dashboard/audit',
                query: {
                  ...(resolvedSearchParams?.action ? { action: resolvedSearchParams.action } : {}),
                  ...(resolvedSearchParams?.tableName ? { tableName: resolvedSearchParams.tableName } : {}),
                  ...(resolvedSearchParams?.fromDate ? { fromDate: resolvedSearchParams.fromDate } : {}),
                  ...(resolvedSearchParams?.toDate ? { toDate: resolvedSearchParams.toDate } : {}),
                  cursor: data.nextCursor,
                },
              }}
            >
              Load more
            </Link>
          </Button>
        </div>
      )}
    </>
  );
}

function Metric({
  icon: Icon,
  label,
  value,
  detail,
  danger = false,
}: {
  icon: React.ComponentType<{ className?: string }>;
  label: string;
  value: string;
  detail: string;
  danger?: boolean;
}) {
  return (
    <div className="rounded-sm border border-ink-200 bg-white p-4 shadow-sm">
      <div className="flex items-center justify-between gap-3">
        <Icon className={danger ? 'h-5 w-5 text-danger' : 'h-5 w-5 text-accent'} />
        <Badge variant={danger ? 'danger' : 'outline'}>{label}</Badge>
      </div>
      <p className="mt-4 font-display text-3xl font-medium text-ink-950">{value}</p>
      <p className="mt-1 text-xs text-ink-500">{detail}</p>
    </div>
  );
}

function DateField({ name, label, value }: { name: string; label: string; value: string }) {
  return (
    <div className="space-y-1">
      <label className="block text-[10px] font-medium uppercase tracking-[0.14em] text-ink-500">
        {label}
      </label>
      <div className="relative">
        <CalendarDays className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-ink-400" />
        <input
          name={name}
          type="date"
          defaultValue={value}
          className="h-10 w-full rounded-sm border border-ink-200 bg-white pl-9 pr-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent"
        />
      </div>
    </div>
  );
}

function ActionBadge({ action }: { action: string }) {
  const variant: 'success' | 'warning' | 'danger' | 'default' =
    action === 'INSERT'
      ? 'success'
      : action === 'UPDATE'
        ? 'warning'
        : action === 'DELETE'
          ? 'danger'
          : 'default';
  return <Badge variant={variant}>{action}</Badge>;
}

function ChangedFields({ fields }: { fields: string[] }) {
  if (fields.length === 0) return <span className="text-xs text-ink-400">No field diff</span>;
  return (
    <div className="flex flex-wrap gap-1">
      {fields.slice(0, 5).map((field) => (
        <Badge key={field} variant={isSensitiveField(field) ? 'warning' : 'outline'}>
          <span className="font-mono text-[10px]">{field}</span>
        </Badge>
      ))}
      {fields.length > 5 && (
        <Badge variant="outline">
          +{fields.length - 5}
        </Badge>
      )}
    </div>
  );
}

function Th({ children }: { children: React.ReactNode }) {
  return (
    <th className="px-4 py-3 text-[10px] font-medium uppercase tracking-[0.14em] text-ink-500">
      {children}
    </th>
  );
}

function Td({ children }: { children: React.ReactNode }) {
  return <td className="px-4 py-3 align-top">{children}</td>;
}

function buildSummary(items: AuditEntry[]) {
  const tables = new Set(items.map((item) => item.tableName));
  return {
    updates: items.filter((item) => item.action === 'UPDATE').length,
    deletes: items.filter((item) => item.action === 'DELETE').length,
    tables: tables.size,
  };
}

function isSensitiveField(field: string): boolean {
  const normalized = field.toLowerCase();
  return normalized.includes('password') || normalized.includes('token') || normalized.includes('secret');
}
